services:
  bfi-staging-traefik-external:
    image: traefik:v2.10
    container_name: bfi-staging-traefik-external
    env_file:
      - .env.staging
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.instance`, `external`)"
      - "--entrypoints.web.address=:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
    ports:
      - "${TRAEFIK_EXTERNAL_HOST_PORT}:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
    networks:
      - bfi-staging-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"

  bfi-staging-traefik-internal:
    image: traefik:v2.10
    container_name: bfi-staging-traefik-internal
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.instance`, `internal`)"
      - "--entrypoints.web.address=:${TRAEFIK_INTENAL_CONTAINER_PORT}"
    networks:
      - bfi-staging-net
    env_file:
      - .env.staging
    depends_on:
      - bfi-staging-service-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.instance=internal"

  bfi-staging-service-gateway:
    image: braceforimpact/bfi-staging-service-gateway:latest
    container_name: bfi-staging-service-gateway
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - bfi-staging-net
    env_file:
      - ./.env.gateway.staging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=${PORT}"

  bfi-staging-service-monitor:
    image: braceforimpact/bfi-staging-service-monitor:latest
    container_name: bfi-staging-service-monitor
    env_file:
      - ./.env.monitor.staging
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - bfi-staging-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"
      - "traefik.http.routers.monitor.rule=PathPrefix(`/api/monitor`)"
      - "traefik.http.services.monitor.loadbalancer.server.port=${PORT}"

  bfi-staging-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: bfi-staging-zookeeper
    env_file:
      - .env.staging
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - bfi-staging-net

  bfi-staging-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bfi-staging-kafka
    env_file:
      - .env.staging
    depends_on:
      - bfi-staging-zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - bfi-staging-net

  bfi-staging-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop-staging
    env_file:
      - .env.staging
    environment:
      - KAFKA_BROKERCONNECT=${KAFKA_BROKERCONNECT}
    ports:
      - "${KAFDROP_HOST_PORT}:${KAFDROP_CONTAINER_PORT}"
    networks:
      - bfi-staging-net

networks:
  bfi-staging-net:
    driver: bridge
