services:
  # External Traefik - only exposes /api -> gateway
  bfi-dev-traefik-external:
    image: traefik:v2.10
    container_name: bfi-dev-traefik-external
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.instance`, `external`)"
      - "--entrypoints.web.address=:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
    ports:
      - "${TRAEFIK_EXTERNAL_HOST_PORT}:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
      - "${TRAEFIK_EXTERNAL_HOST_UI_PORT}:${TRAEFIK_EXTERNAL_CONTAINER_UI_PORT}"
    networks:
      - bfi-dev-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"



  # Internal Traefik - handles internal service load balancing
  bfi-dev-traefik-internal:
    image: traefik:v2.10
    container_name: bfi-dev-traefik-internal
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.instance`, `internal`)"
      - "--entrypoints.web.address=:${TRAEFIK_INTENAL_CONTAINER_PORT}"
    networks:
      - bfi-dev-net
    depends_on:
      - bfi-dev-service-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${TRAEFIK_INTERNAL_HOST_UI_PORT}:${TRAEFIK_INTERNAL_CONTAINER_UI_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.instance=internal"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"



  # Gateway Service
  bfi-dev-service-gateway:
    build:
      context: ../bfi-service-gateway
      target: dev
    image: bfi-dev-service-gateway
    env_file:
      - ./service-envs/.env.gateway.development
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - bfi-dev-net
    volumes:
      - ../bfi-service-gateway:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ../bfi-shared:/app/node_modules/@brace-for-impact/bfi-shared
    ports:
      - "${HOST_PORT_GATEWAY}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=${PORT}"

    # Monitor Service
  bfi-dev-service-monitor:
    build:
      context: ../bfi-service-monitor
      target: dev
    image: bfi-dev-service-monitor
    env_file:
      - ./service-envs/.env.monitor.development
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - bfi-dev-net
    volumes:
      - ../bfi-service-monitor:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${HOST_PORT_MONITOR}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"
      - "traefik.http.routers.monitor.rule=PathPrefix(`/api/monitor`)"
      - "traefik.http.services.monitor.loadbalancer.server.port=${PORT}"

  bfi-dev-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: bfi-dev-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - bfi-dev-net

  bfi-dev-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bfi-dev-kafka
    depends_on:
      - bfi-dev-zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - bfi-dev-net
    ports:
      - "${KAFKA_HOST_PORT}:${KAFKA_CONTAINER_PORT}"

  bfi-dev-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    environment:
      - KAFKA_BROKERCONNECT=${KAFKA_BROKERCONNECT}
    ports:
      - "${KAFDROP_HOST_PORT}:${KAFDROP_CONTAINER_PORT}"
    networks:
      - bfi-dev-net

networks:
  bfi-dev-net:
    driver: bridge