services:
  # Single External Traefik - exposes and load balances directly to services
  bfi-dev-traefik:
    image: traefik:v2.10
    container_name: bfi-dev-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
    ports:
      - "${TRAEFIK_EXTERNAL_HOST_PORT}:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
      - "${TRAEFIK_EXTERNAL_HOST_UI_PORT}:${TRAEFIK_EXTERNAL_CONTAINER_UI_PORT}"
    networks:
      - bfi-dev-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${TRAEFIK_EXTERNAL_CONTAINER_UI_PORT}/dashboard/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Monitor Service - exposed via Traefik
  bfi-dev-service-monitor:
    build:
      context: ../bfi-service-monitor
      target: dev
    image: bfi-dev-service-monitor
    env_file:
      - ./service-envs/.env.monitor.development
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - bfi-dev-net
    volumes:
      - ../bfi-service-monitor:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${HOST_PORT_MONITOR}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.rule=PathPrefix(`/api/monito`)"
      - "traefik.http.services.monitor.loadbalancer.server.port=${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${PORT}/api/monitor/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      bfi-dev-kafka:
        condition: service_healthy
      bfi-dev-traefik:
        condition: service_healthy
  
  # Auth Service - exposed via Traefik
  bfi-dev-service-auth:
    build:
      context: ../bfi-service-auth
      target: dev
    image: bfi-dev-service-auth
    env_file:
      - ./service-envs/.env.auth.development
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - bfi-dev-net
    volumes:
      - ../bfi-service-auth:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${HOST_PORT_AUTH}:${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${PORT}/api/auth/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      bfi-dev-kafka:
        condition: service_healthy
      bfi-dev-traefik:
        condition: service_healthy

  # Zookeeper
  bfi-dev-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: bfi-dev-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - bfi-dev-net
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/${ZOOKEEPER_CLIENT_PORT}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka
  bfi-dev-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bfi-dev-kafka
    depends_on:
      bfi-dev-zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - bfi-dev-net
    ports:
      - "${KAFKA_HOST_PORT}:${KAFKA_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/${KAFKA_CONTAINER_PORT}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafdrop
  bfi-dev-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    environment:
      - KAFKA_BROKERCONNECT=${KAFKA_BROKERCONNECT}
    ports:
      - "${KAFDROP_HOST_PORT}:${KAFDROP_CONTAINER_PORT}"
    networks:
      - bfi-dev-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${KAFDROP_CONTAINER_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      bfi-dev-kafka:
        condition: service_healthy

networks:
  bfi-dev-net:
    driver: bridge