services:
  bfi-traefik-external:
    image: traefik:v2.10
    container_name: bfi-traefik-external
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.instance`, `external`)"
      - "--entrypoints.web.address=:${TRAEFIK_EXTERNAL_CONTAINER_PORT}"
    ports:
      - "${TRAEFIK_EXTERNAL_HOST_UI_PORT}:${TRAEFIK_EXTERNAL_CONTAINER_UI_PORT}"
    networks:
      - bfi-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"

  bfi-traefik-internal:
    image: traefik:v2.10
    container_name: bfi-traefik-internal
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.instance`, `internal`)"
      - "--entrypoints.web.address=:${TRAEFIK_INTENAL_CONTAINER_PORT}"
    networks:
      - bfi-net
    depends_on:
      - bfi-service-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${TRAEFIK_INTERNAL_HOST_UI_PORT}:${TRAEFIK_INTERNAL_CONTAINER_UI_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.instance=internal"

  bfi-service-gateway:
    image: bfi-service-gateway
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    networks:
      - bfi-net
    labels:
      - "traefik.enable=true"
      - "traefik.instance=external"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=${PORT}"

  bfi-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: bfi-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - bfi-net

  bfi-kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bfi-kafka
    depends_on:
      - bfi-zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - bfi-net

  bfi-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    environment:
      - KAFKA_BROKERCONNECT=${KAFKA_BROKERCONNECT}
    ports:
      - "${KAFDROP_HOST_PORT}:${KAFDROP_CONTAINER_PORT}"
    networks:
      - bfi-net

networks:
  bfi-net:
    driver: bridge
